version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: "@kth/http-responses"
    versions:
    - 1.0.48
    - 1.0.50
  - dependency-name: kth-node-log
    versions:
    - 3.1.4
