# --- START OF DON'T MODIFY ----
name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: github.com_jotunskij

jobs:
- job: run_evolene
  displayName: Build with Evolene
  continueOnError: true
  workspace:
    clean: outputs
  variables:
    group: evolene-variable-group
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - bash: pip install --upgrade pip

  - checkout: evolene
    path: s/evolene
  - checkout: self
    path: s/self

  - bash: pip install pipenv

  - bash: pipenv install
    workingDirectory: $(EVOLENE_DIRECTORY)

  - bash: $(EVOLENE_DIRECTORY)/run.sh
    workingDirectory: $(WORKSPACE)
    env: 
      REGISTRY_PASSWORD: $(Secret.Registry.Password)

# --- END OF DON'T MODIFY ----

      # Evolene environment flags
      SLACK_CHANNELS: "#team-pipeline-build"
      # DEBUG: 1
      # SKIP_DRY_RUN: 1
      
