web:
  image: kth-docker-registry.sys.kth.se/kth-azure-app:latest
  ports:
   - "80:3000"

# Web letar efter redis på kth-redis.westeurope.cloudapp.azure.com
redis:
  image: redis
  ports:
   - "6379:6379"
