version: "3"

#
# Run this integration test by running:
# ID=$(docker build -q .) && LOCAL_IMAGE_ID=$ID docker-compose -f docker-compose-integration-tests.yml up --abort-on-container-exit --always-recreate-deps
#
# docker images | grep kth-azure-app_app | awk '{ print $3 }' | xargs docker inspect | grep se.kth.imageVersion
services:
  #############################################
  # Start http://web:3000/
  #############################################
  web:
    # if not --build and kth-azure-app already exists in
    # your local computers registry 'image' is used.
    image: $LOCAL_IMAGE_ID

    # Possible configuration for the app.
    environment:
      - DB_URL="https://example.com:1234"
      - DB_USER="admin"
      - ENV_TEST="SECRET_VALUE_ON__MONITOR."
      - FLOTTSBRO_API_KEY

    ports:
      - 3000

  #############################################
  # Start the client running tests
  # agains http://web:3000/
  #############################################
  integration-tests:
    # Build client image and run tests
    # from inside that.
    build: ./tests/integration-tests
    depends_on:
      - web
