version: '2'
services:
  web:
    extends:
      file: common-services.yml
      service: frontend
    image: kth-docker-registry.sys.kth.se/kth-azure-app:0.15
    ports:
      - 3000
    depends_on:
      - redis

  redis:
    extends:
      file: common-services.yml
      service: backend
    image: redis:latest
    ports:
      - 6379

networks:
  application_frontend:
    driver: overlay
  application_backend:
    driver: overlay

