version: '2'
services:
  web:
    image: kth-docker-registry.sys.kth.se/kth-azure-app:latest
    ports:
      - "3000"
    networks:
      - testnet
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - testnet

networks:
  testnet:
    driver: overlay