version: '3'

services:
  web:
    build: .
    image: ${evolene-registry}kth-azure-app${evolene-tag}
    ports:
      - 3000

  integration-tests:
    build: ./tests/integration-tests
    depends_on:
      - web
