version: '2'
services:
  web:
    extends:
      file: common-services.yml
      service: frontend
    image: kth-docker-registry.sys.kth.se/kth-azure-app:1.0
    environment:
      # SERVICE_ID is used to create valid DNS entries for registrator -> SkyDNS
      SERVICE_ID : "$COMPOSE_PROJECT_NAME-web"
      SERVICE_TAGS : "app,kth,web,nodejs"
      SERVICE_PUBLISH : "/_azure/app"
    dns: 10.1.1.100
    ports:
      - 3000
    depends_on:
      - redis

  redis:
    extends:
      file: common-services.yml
      service: backend
    image: redis:latest
    environment:
      SERVICE_ID : "$COMPOSE_PROJECT_NAME-redis"
      SERVICE_TAGS : "app,storage,redis,stateless,no-scale"
    dns: 10.1.1.100
    ports:
      - 6379
