version: '3'

services:
  unit_tests:
    image: $LOCAL_IMAGE_ID

    environment:
      - FLOTTSBRO_API_KEY
      - APPLICATION_NAME
      - MONGODB_CONNECTION_STRING
      - A_KEY

    volumes:
      - ${WORKSPACE}/tests:/tests
      
    tty: true
    command: ["sh", "-c", "npm install --development && npm test"]

