version: "3"

#
# echo "Running unit tests inside 🐳 Docker Compose"
#
# ID=$(docker build -q .) && \
#     WORKSPACE=$(pwd) \LOCAL_IMAGE_ID=$ID \
#     docker-compose \
#         --file docker-compose-unit-tests-new.yml up \
#         --force-recreate \
#         --abort-on-container-exit \
#         --always-recreate-deps \
#         --no-log-prefix \
#         --quiet-pull \
#         --build
    
services:
  #############################################
  # Start http://web:3000/
  #############################################
  web:
    # if not --build and kth-azure-app already exists in
    # your local computers registry 'image' is used.
    image: $LOCAL_IMAGE_ID

    # Possible configuration for the app.
    environment:
      - DB_URL="https://example.com:1234"
      - DB_USER="admin"
      - ENV_TEST="SECRET_VALUE_ON__MONITOR."
      - FLOTTSBRO_API_KEY

    ports:
      - 3000

  #############################################
  # Start the client running tests
  # agains http://web:3000/
  #############################################
  integration-tests:
    # Build client image and run tests
    # from inside that.
    build: ./tests/integration-tests
    environment:
      - WEB

    depends_on:
      - web
