version: '3'

services:

  web:
    build: .
    environment:
      NON_SECRET_SETTING: "This only exists for this service and this cluster"
      ENV_TEST: "En miljovariabel"

    ports:
      - 3000:3000
