version: '2'
services:
  web:
    extends:
      file: common-services.yml
      service: app
    image: kth-docker-registry.sys.kth.se/kth-azure-app:V.0.11
    ports:
      - 3000
    links:
      - redis

  redis:
    extends:
      file: common-services.yml
      service: app
    image: redis:latest
    ports:
      - 6379

# TODO(tinglev): overlays are suggested to have hard coded subnets
# TODO(tinglev): to not interfere with already existing infrastructure
# TODO(tinglev): not a problem as long as we run on clusternet (cluster wide overlay)
#networks:
#  appnet:
#    driver: overlay
networks:
  clusternet:
    external: true

