version: '2'

#
# For development
#
services:
  web:
    #image: kth-docker-registry.sys.kth.se/kth-azure-app:1.1.2
    build: .
    ports:
      - 3000
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379
