version: '3'

services:
  web:
    build: .
    image: kth-azure-app
    
    environment:
      DB_URL: "https://example.com:1234"
      DB_USER: "admin"

    ports:
      - 3000
    depends_on:
      - redis
      
  redis:
    image: redis:3.2.6-alpine

  integration-tests:
    build: ./tests/integration-tests
    depends_on:
      - web
