version: '2'
services:
  web:
    extends:
      file: common-services.yml
      service: app
    image: kth-docker-registry.sys.kth.se/kth-azure-app:latest
    ports:
      - "3000"
    links:
      - redis

  redis:
    extends:
      file: common-services.yml
      service: app
    image: redis
    ports:
      - "6379"

networks:
  appnet:
    driver: overlay