version: '2'

###############################################
# SERVICES
###############################################
services:
  #
  # Web application
  #
  web:
    extends:
      file: .docker/compose/common-services.yml
      service: frontend
    image: kth-docker-registry.sys.kth.se/kth-azure-app:1.1
    environment:
      # SERVICE_ID is used to create valid DNS entries for registrator -> SkyDNS
      SERVICE_ID : "$COMPOSE_PROJECT_NAMEweb"
      SERVICE_ID : "web"
      SERVICE_TAGS : "app,kth,web,nodejs"
      SERVICE_PUBLISH : "/_azure/_monitor"
    ports:
      - 3000
    depends_on:
      - redis

  #
  # Redis application cache
  #
  redis:
    extends:
      file: .docker/compose/common-services.yml
      service: backend
    image: redis:latest
    environment:
      SERVICE_ID : "$COMPOSE_PROJECT_NAMEredis"
      SERVICE_ID : "redis"
      SERVICE_TAGS : "app,storage,redis,stateless,no-scale"
      SERVICE_PERSISTENT : "yes"
    ports:
      - 6379

###############################################
# NETWORKS
###############################################
networks:
  application_frontend:
    driver: overlay
  application_backend:
    driver: overlay
