# This is a basic workflow to help you get started with Actions

name: Build with Evolene

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Checks-out Evolene to $GITHUB_WORKSPACE/evolene
      - uses: actions/checkout@v2
        with:
          repository: KTH/evolene
          path: 'evolene'

      # Runs a single command using the runners shell
      - name: Install Evolene dependencies
        run: |
          cd $GITHUB_WORKSPACE/evolene
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      # Runs a set of commands using the runners shell
      - name: Build with Evolene
        run: |
          cd $GITHUB_WORKSPACE
          ls -al
          ./evolene/run.sh
