name: Evolene CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  CI:
    name: Continuous Integration 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build, Test and Push with Evolene 
        run: |
            SLACK_CHANNELS=#team-pipeline-build \
            BUILD_INFORMATION_OUTPUT_FILE='/config/version.js' \
            EVOLENE_TEST_SECRETS=${{secrets.EVOLENE_TEST_SECRETS}} \
            ${{ secrets.EVOLENE_RUN_COMMAND }}
