name: Continuous Integration with Evolene

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: KTH - Build, Test and Push With Evolene         
        run: ${{ secrets.EVOLENE_RUN_COMMAND }}
  Envs:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Ubuntu environment variables         
        run: set
